version: '3.8'
services:
  cdr-worker:
    image: ghcr.io/hzis/cdrviewer_worker/cdr-worker:latest
    container_name: cdr-worker-01
    restart: always
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - cdr-network

networks:
  cdr-network:
    driver: bridge
